/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package solucionadorsistemaslineares;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.text.JTextComponent;

/**
 *
 * @author luiza
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpMetodo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        radEliGauss = new javax.swing.JRadioButton();
        radMetJacobi = new javax.swing.JRadioButton();
        radMetSeidel = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTamanho = new javax.swing.JTextPane();
        painelMatriz = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnExecutar = new javax.swing.JButton();
        lblErro = new javax.swing.JLabel();
        txtErro = new javax.swing.JTextField();
        lblInteracao = new javax.swing.JLabel();
        txtInteracao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel1.setText("Solucionador de Sistemas Lineares");

        grpMetodo.add(radEliGauss);
        radEliGauss.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        radEliGauss.setText("Eliminação de Gauss");
        radEliGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEliGaussActionPerformed(evt);
            }
        });

        grpMetodo.add(radMetJacobi);
        radMetJacobi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        radMetJacobi.setText("Método de Jacobi");
        radMetJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMetJacobiActionPerformed(evt);
            }
        });

        grpMetodo.add(radMetSeidel);
        radMetSeidel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        radMetSeidel.setText("Método de Gauss-Seidel");
        radMetSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMetSeidelActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione o método desejado:");

        jLabel3.setText("Tamanho da matriz (NxN):");

        txtTamanho.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTamanhoCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(txtTamanho);

        painelMatriz.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setText("Digite os coeficientes da matriz A e o vetor de termos independentes b (campos em verde)");

        btnExecutar.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        btnExecutar.setText("Executar");
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });

        lblErro.setText("Precisão de erro:");

        txtErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtErroActionPerformed(evt);
            }
        });

        lblInteracao.setText("Número máximo de interações:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radEliGauss)
                                .addGap(18, 18, 18)
                                .addComponent(radMetJacobi)
                                .addGap(18, 18, 18)
                                .addComponent(radMetSeidel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtErro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblInteracao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtInteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(painelMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btnExecutar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radEliGauss)
                    .addComponent(radMetJacobi)
                    .addComponent(radMetSeidel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErro)
                    .addComponent(lblInteracao)
                    .addComponent(txtInteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtErro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExecutar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radEliGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEliGaussActionPerformed
        txtErro.setText("");
        txtInteracao.setText("");
        
        javax.swing.border.Border bordaPadrao = javax.swing.UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border");

        txtErro.setBorder(bordaPadrao);
        txtInteracao.setBorder(bordaPadrao);
        
        txtErro.setEnabled(false);
        txtInteracao.setEnabled(false);
    }//GEN-LAST:event_radEliGaussActionPerformed

    private void radMetJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMetJacobiActionPerformed
        txtErro.setEnabled(true);
        txtInteracao.setEnabled(true);
    }//GEN-LAST:event_radMetJacobiActionPerformed

    private javax.swing.JTextField[][] camposA;
    private javax.swing.JTextField[] camposB;
    private void txtTamanhoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTamanhoCaretUpdate
        try {
            int n = Integer.parseInt(txtTamanho.getText());
            painelMatriz.removeAll();

            // Configura: N linhas e N + 1 colunas
            painelMatriz.setLayout(new java.awt.GridLayout(n, n + 1, 5, 5));

            camposA = new javax.swing.JTextField[n][n];
            camposB = new javax.swing.JTextField[n];

            for (int i = 0; i < n; i++) {
                // 1. Adiciona os campos da Matriz A (Coeficientes)
                for (int j = 0; j < n; j++) {
                    camposA[i][j] = new javax.swing.JTextField();
                    painelMatriz.add(camposA[i][j]);
                }

                // 2. Adiciona o campo do Termo Independente (Vetor b) no final da linha
                camposB[i] = new javax.swing.JTextField();
                // Dica visual: mude a cor para o usuário saber que é o termo independente
                camposB[i].setBackground(new java.awt.Color(200, 255, 200)); 
                painelMatriz.add(camposB[i]);
            }

            painelMatriz.revalidate();
            painelMatriz.repaint();
        } catch (Exception e) {
            // tratamento de erro
        }
    }//GEN-LAST:event_txtTamanhoCaretUpdate

    public boolean validarMatriz() {
        Border bordaPadrao = UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border");
        // 🔹 Valida matriz A

        for (int i = 0; i < camposA.length; i++) {
            for (int j = 0; j < camposA[i].length; j++) {

                JTextField campo = camposA[i][j];
                campo.setBorder(bordaPadrao);
                String texto = campo.getText().trim();

                // Campo vazio
                if (texto.isEmpty()) {
                    campo.setBorder(BorderFactory.createLineBorder(Color.RED));
                    JOptionPane.showMessageDialog(null,"Preencha todos os campos da matriz!\nUse 0 quando não houver valor.","ERRO!!!",JOptionPane.ERROR_MESSAGE);
                    return false;
                }

                // Não é número
                if (!texto.matches("-?\\d+(\\.\\d+)?")) {
                    campo.setBorder(BorderFactory.createLineBorder(Color.RED));
                    JOptionPane.showMessageDialog(null,"Digite apenas números na matriz!","ERRO!!!",JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
        }

        // 🔹 Valida vetor B
        for (int i = 0; i < camposB.length; i++) {

            JTextField campo = camposB[i];
            campo.setBorder(bordaPadrao);
            String texto = campo.getText().trim();

            if (texto.isEmpty()) {
                campo.setBorder(BorderFactory.createLineBorder(Color.RED));
                JOptionPane.showMessageDialog(null, "Preencha todos os termos independentes!","ERRO!!!",JOptionPane.ERROR_MESSAGE);
                return false;
            }

            if (!texto.matches("-?\\d+(\\.\\d+)?")) {
                campo.setBorder(BorderFactory.createLineBorder(Color.RED));
                JOptionPane.showMessageDialog(null,"Digite apenas números no vetor B!","ERRO!!!", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        return true;
    }

    
    public boolean validarCampos(JTextComponent... campos) {
        boolean valido = true;

        for (JTextComponent campo : campos) {
            campo.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));

            if (campo.getText().trim().isEmpty()) {
                campo.setBorder(BorderFactory.createLineBorder(Color.RED));
                valido = false;
            }
        }

        return valido;
    }
    public boolean validarNumero(JTextComponent campo) {
        String texto = campo.getText().trim();
        return texto.matches("\\d+");
    }
    
    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        if(radEliGauss.isSelected()){
            if(!validarCampos(txtTamanho)){
                JOptionPane.showMessageDialog(null, "O campo tamanho da matriz(NxN) é obrigatório!","ERRO!!!", JOptionPane.ERROR_MESSAGE);
                return;
            }else if (!validarNumero(txtTamanho)) {
                JOptionPane.showMessageDialog(null, "Digite um número válido!");
                return;
            } else if (validarMatriz()) {
                // chamar a classe Eliminação de Gauss
                JOptionPane.showMessageDialog(null, "RESOLVENDO SISTEMA POR ELIMINAÇÃO DE GAUSS!","AVISO!!!", JOptionPane.INFORMATION_MESSAGE);
                return;
                
            }
        }else if (radMetJacobi.isSelected()|| radMetSeidel.isSelected()){            
            if(!validarCampos(txtTamanho,txtErro,txtInteracao)){
                JOptionPane.showMessageDialog(null, "Os campos tamanho da matriz (NxN), presição de erro \n e número máximo de interações são todos obrigatórios!","ERRO!!!", JOptionPane.ERROR_MESSAGE);
                return;
            }else if (!validarNumero(txtTamanho)) {
                JOptionPane.showMessageDialog(null, "Digite um número válido!");
                return;
            } else if (validarMatriz()) {
                if(radMetJacobi.isSelected()){
                // chamar a classe METODO DE JACOBI 
                    JOptionPane.showMessageDialog(null, "RESOLVENDO SISTEMA POR MÉTODO DE JACOBI!","AVISO!!!", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                else{
                    // chamar a classe METODO DE SEIDEL
                    JOptionPane.showMessageDialog(null, "RESOLVENDO SISTEMA POR MÉTODO DE SEIDEL!","AVISO!!!", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }

        }else{
            JOptionPane.showMessageDialog(null, "Selecione um método", "ERRO!!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnExecutarActionPerformed

    private void radMetSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMetSeidelActionPerformed
        txtErro.setEnabled(true);
        txtInteracao.setEnabled(true);
    }//GEN-LAST:event_radMetSeidelActionPerformed

    private void txtErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtErroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtErroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecutar;
    private javax.swing.ButtonGroup grpMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblInteracao;
    private javax.swing.JPanel painelMatriz;
    private javax.swing.JRadioButton radEliGauss;
    private javax.swing.JRadioButton radMetJacobi;
    private javax.swing.JRadioButton radMetSeidel;
    private javax.swing.JTextField txtErro;
    private javax.swing.JTextField txtInteracao;
    private javax.swing.JTextPane txtTamanho;
    // End of variables declaration//GEN-END:variables
}
