/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package solucionadorsistemaslineares;

/**
 *
 * @author luiza
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpMetodo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        radEliGauss = new javax.swing.JRadioButton();
        radMetJacobi = new javax.swing.JRadioButton();
        radMetSeidel = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTamanho = new javax.swing.JTextPane();
        painelMatriz = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Solucionador de Sistemas Lineares");

        grpMetodo.add(radEliGauss);
        radEliGauss.setText("Eliminação de Gauss");
        radEliGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEliGaussActionPerformed(evt);
            }
        });

        grpMetodo.add(radMetJacobi);
        radMetJacobi.setText("Método de Jacobi");
        radMetJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMetJacobiActionPerformed(evt);
            }
        });

        grpMetodo.add(radMetSeidel);
        radMetSeidel.setText("Método de Gauss-Seidel");

        jLabel2.setText("Selecione o método desejado:");

        jLabel3.setText("Tamanho da matriz (NxN):");

        txtTamanho.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTamanhoCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(txtTamanho);

        painelMatriz.setLayout(new java.awt.GridLayout());

        jLabel4.setText("Coeficientes da matriz:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radEliGauss)
                                .addGap(18, 18, 18)
                                .addComponent(radMetJacobi)
                                .addGap(18, 18, 18)
                                .addComponent(radMetSeidel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(painelMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radEliGauss)
                    .addComponent(radMetJacobi)
                    .addComponent(radMetSeidel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(painelMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radEliGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEliGaussActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radEliGaussActionPerformed

    private void radMetJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMetJacobiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radMetJacobiActionPerformed

    private javax.swing.JTextField[][] camposA;
    private javax.swing.JTextField[] camposB;
    private void txtTamanhoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTamanhoCaretUpdate
        try {
            int n = Integer.parseInt(txtTamanho.getText());
            painelMatriz.removeAll();

            // Configura: N linhas e N + 1 colunas
            painelMatriz.setLayout(new java.awt.GridLayout(n, n + 1, 5, 5));

            camposA = new javax.swing.JTextField[n][n];
            camposB = new javax.swing.JTextField[n];

            for (int i = 0; i < n; i++) {
                // 1. Adiciona os campos da Matriz A (Coeficientes)
                for (int j = 0; j < n; j++) {
                    camposA[i][j] = new javax.swing.JTextField();
                    painelMatriz.add(camposA[i][j]);
                }

                // 2. Adiciona o campo do Termo Independente (Vetor b) no final da linha
                camposB[i] = new javax.swing.JTextField();
                // Dica visual: mude a cor para o usuário saber que é o termo independente
                camposB[i].setBackground(new java.awt.Color(200, 255, 200)); 
                painelMatriz.add(camposB[i]);
            }

            painelMatriz.revalidate();
            painelMatriz.repaint();
        } catch (Exception e) {
            // tratamento de erro
        }
    }//GEN-LAST:event_txtTamanhoCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grpMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelMatriz;
    private javax.swing.JRadioButton radEliGauss;
    private javax.swing.JRadioButton radMetJacobi;
    private javax.swing.JRadioButton radMetSeidel;
    private javax.swing.JTextPane txtTamanho;
    // End of variables declaration//GEN-END:variables
}
